-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 17:36:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eat2gather
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eat2gather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eat2gather` DEFAULT CHARACTER SET utf8 ;
USE `eat2gather` ;

-- -----------------------------------------------------
-- Table `eat2gather`.`food_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`food_type` (
  `foodtype_id` INT(11) NOT NULL AUTO_INCREMENT,
  `foodtype_name` VARCHAR(45) NOT NULL,
  `tastes` ENUM('spicy', 'sweet', 'salty', 'sour', 'vegetarian') NOT NULL,
  `region` ENUM('korean', 'japanese', 'chinese', 'european', 'mexican', 'american', 'african', 'indian') NOT NULL,
  PRIMARY KEY (`foodtype_id`),
  UNIQUE INDEX `foodtype_id_UNIQUE` (`foodtype_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`happened`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`happened` (
  `meeting_id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `meeting_datetime` DATETIME NOT NULL,
  `max_participants` INT(11) NOT NULL,
  PRIMARY KEY (`meeting_id`),
  UNIQUE INDEX `meeting_id_UNIQUE` (`meeting_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`restaurant` (
  `restaurant_id` INT(11) NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `restaurant_email` VARCHAR(45) NOT NULL,
  `restaurant_location` VARCHAR(45) NOT NULL,
  `restaurant_phone` INT(11) NOT NULL,
  `restaurant_type` ENUM('cafe', 'restaurant', 'pub', 'cafeteria') NOT NULL,
  PRIMARY KEY (`restaurant_id`),
  UNIQUE INDEX `restaurant_id_UNIQUE` (`restaurant_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`upcoming`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`upcoming` (
  `meeting_id` INT(11) NOT NULL AUTO_INCREMENT,
  `meeting_datetime` DATETIME NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `max_participants` INT(11) NOT NULL,
  PRIMARY KEY (`meeting_id`),
  UNIQUE INDEX `meeting_id_UNIQUE` (`meeting_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`meeting` (
  `meeting_id` INT(11) NOT NULL AUTO_INCREMENT,
  `meeting_name` VARCHAR(15) NOT NULL,
  `meeting_datetime` DATETIME NOT NULL,
  `max_participants` INT(11) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `timepassed` TINYINT(4) NOT NULL DEFAULT '0',
  `restaurant_restaurant_id` INT(11) NOT NULL,
  `upcoming_meeting_id` INT(11) NOT NULL,
  `happened_meeting_id` INT(11) NOT NULL,
  PRIMARY KEY (`meeting_id`),
  UNIQUE INDEX `meeting_id_UNIQUE` (`meeting_id` ASC),
  INDEX `fk_meeting_restaurant1_idx` (`restaurant_restaurant_id` ASC),
  INDEX `fk_meeting_upcoming1_idx` (`upcoming_meeting_id` ASC),
  INDEX `fk_meeting_happened1_idx` (`happened_meeting_id` ASC),
  CONSTRAINT `fk_meeting_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `eat2gather`.`restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_meeting_upcoming1`
    FOREIGN KEY (`upcoming_meeting_id`)
    REFERENCES `eat2gather`.`upcoming` (`meeting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_meeting_happened1`
    FOREIGN KEY (`happened_meeting_id`)
    REFERENCES `eat2gather`.`happened` (`meeting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`requests` (
  `request_id` INT(11) NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(100) NOT NULL,
  `acceptance` TINYINT(4) NOT NULL,
  `upcoming_meeting_id` INT(11) NOT NULL,
  PRIMARY KEY (`request_id`),
  UNIQUE INDEX `request_id_UNIQUE` (`request_id` ASC),
  INDEX `fk_requests_upcoming1_idx` (`upcoming_meeting_id` ASC),
  CONSTRAINT `fk_requests_upcoming1`
    FOREIGN KEY (`upcoming_meeting_id`)
    REFERENCES `eat2gather`.`upcoming` (`meeting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`review` (
  `review_id` INT(11) NOT NULL AUTO_INCREMENT,
  `review` VARCHAR(150) NOT NULL,
  `restaurant_restaurant_id` INT(11) NOT NULL,
  PRIMARY KEY (`review_id`),
  UNIQUE INDEX `review_id_UNIQUE` (`review_id` ASC),
  INDEX `fk_review_restaurant1_idx` (`restaurant_restaurant_id` ASC),
  CONSTRAINT `fk_review_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `eat2gather`.`restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`user` (
  `user_id` VARCHAR(15) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `student_id` INT(11) NOT NULL,
  `bday` DATETIME NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `photo` LONGBLOB NOT NULL,
  `introduction` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`meeting_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`meeting_members` (
  `user_id` VARCHAR(15) NOT NULL,
  `meeting_id` INT(11) NOT NULL,
  `isHost` TINYINT(1) NOT NULL,
  PRIMARY KEY (`meeting_id`),
  INDEX `fk_user_has_meeting_meeting1_idx` (`meeting_id` ASC),
  INDEX `fk_user_has_meeting_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_meeting_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `eat2gather`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_meeting_meeting1`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `eat2gather`.`meeting` (`meeting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eat2gather`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eat2gather`.`menu` (
  `dish` VARCHAR(50) NOT NULL,
  `price` INT NOT NULL,
  `restaurant_id` INT(11) NOT NULL,
  `foodtype_id` INT(11) NOT NULL,
  INDEX `fk_menu_restaurant1_idx` (`restaurant_id` ASC),
  INDEX `fk_menu_food_type1_idx` (`foodtype_id` ASC),
  PRIMARY KEY (`restaurant_id`, `foodtype_id`),
  CONSTRAINT `fk_menu_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `eat2gather`.`restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_food_type1`
    FOREIGN KEY (`foodtype_id`)
    REFERENCES `eat2gather`.`food_type` (`foodtype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
